steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/a2a-immersion-day-template'
      - '-f'
      - 'app/a2a/Dockerfile'
      - '.'
images:
  - 'gcr.io/$PROJECT_ID/a2a-immersion-day-template'
